extends: eslint:recommended

rules:

    # POSSIBLE ERRORS

    for-direction: error
    getter-return: error
    no-compare-neg-zero: error
    no-empty:
        - error
        - allowEmptyCatch: true
    no-inner-declarations:
        - error
        - both
    valid-typeof:
        - error
        - requireStringLiterals: true

    # BEST PRACTICES

    accessor-pairs: error
    array-callback-return: error
    curly: error
    default-case: error
    dot-location:
        - error
        - property
    dot-notation:
        - error
        - allowKeywords: false
    eqeqeq:
        - error
        - smart
    guard-for-in: error
    no-alert: error
    no-caller: error
    no-empty-function: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-floating-decimal: error
    no-implicit-coercion:
        - error
        - boolean: false
    no-implicit-globals: error
    no-implied-eval: error
    no-invalid-this: error
    no-iterator: error
    no-labels: error
    no-lone-blocks: error
    no-loop-func: error
    no-multi-spaces: error
    no-multi-str: error
    no-new: error
    no-new-func: error
    no-new-wrappers: error
    no-octal: error
    no-octal-escape: error
    no-param-reassign:
        - error
        - props: true
    no-proto: error
    no-return-assign: error
    no-script-url: error
    no-self-assign:
        - error
        - props: true
    no-self-compare: error
    no-sequences: error
    no-throw-literal: error
    no-unmodified-loop-condition: error
    no-unused-expressions:
        - error
        - allowTernary: true
          allowShortCircuit: true
    no-useless-call: error
    no-useless-concat: error
    no-useless-escape: error
    no-useless-return: error
    no-with: error
    radix: error
    vars-on-top: error
    wrap-iife:
        - error
        - inside
        - functionPrototypeMethods: true
    yoda: error

    # VARIABLES

    no-catch-shadow: error
    no-label-var: error
    no-shadow-restricted-names: error
    no-undef-init: error
    no-undefined: error
    no-unused-vars:
        - error
        - vars: local
          args: all
    no-use-before-define:
        - error
        - classes: false
          variables: false
