extends: eslint:recommended

rules:

    # POSSIBLE ERRORS

    no-compare-neg-zero: error
    no-empty:
        - error
        - allowEmptyCatch: true
    no-inner-declarations:
        - error
        - both
    valid-typeof:
        - error
        - requireStringLiterals: true

    # BEST PRACTICES

    accessor-pairs: error
    array-callback-return: warn
    curly: warn
    default-case: warn
    dot-location:
        - warn
        - property
    dot-notation:
        - warn
        - allowKeywords: false
    eqeqeq:
        - warn
        - smart
    guard-for-in: warn
    no-alert: warn
    no-caller: error
    no-empty-function: warn
    no-eval: error
    no-extend-native: error
    no-extra-bind: warn
    no-extra-label: warn
    no-floating-decimal: warn
    no-implicit-coercion:
        - warn
        - boolean: false
    no-implicit-globals: warn
    no-implied-eval: error
    no-invalid-this: warn
    no-iterator: error
    no-labels: warn
    no-lone-blocks: warn
    no-loop-func: error
    no-multi-spaces: warn
    no-multi-str: error
    no-new: warn
    no-new-func: error
    no-new-wrappers: warn
    no-octal: error
    no-octal-escape: error
    no-param-reassign:
        - error
        - props: true
    no-proto: error
    no-return-assign: error
    no-script-url: warn
    no-self-assign:
        - error
        - props: true
    no-self-compare: error
    no-sequences: error
    no-throw-literal: warn
    no-unmodified-loop-condition: error
    no-unused-expressions: error
    no-useless-call: warn
    no-useless-concat: warn
    no-useless-escape: warn
    no-useless-return: warn
    no-with: error
    radix: warn
    vars-on-top: warn
    wrap-iife:
        - warn
        - inside
        - functionPrototypeMethods: true
    yoda: warn

    # VARIABLES

    no-catch-shadow: error
    no-label-var: warn
    no-shadow:
        - warn
        - builtinGlobals: true
    no-shadow-restricted-names: error
    no-undef-init: warn
    no-undefined: warn
    no-unused-vars:
        - error
        - vars: local
          args: all
    no-use-before-define:
        - error
        - classes: false
          variables: false
